stages:
  - build
  - publish
  - publish-to-rubygems

variables:
  RUBY_IMAGE: "ruby:3.1.2"
  GEM_NAME: "trustcaptcha"

before_script:
  - gem install bundler
  - bundle install

build:
  image: $RUBY_IMAGE
  stage: build
  tags:
    - build
  script:
    - gem build $GEM_NAME.gemspec
    - ruby tests/test_captcha_manager.rb
  artifacts:
    paths:
      - ./*.gem
  only:
    - branches
    - tags

publish-to-rubygems:
  image: $RUBY_IMAGE
  stage: publish-to-rubygems
  tags:
    - build
  script:
    - sed -i "s/0.1.0/${CI_COMMIT_TAG}/" $GEM_NAME.gemspec
    - gem build $GEM_NAME.gemspec
    - mkdir -p ~/.gem
    - |
      cat <<EOF > ~/.gem/credentials
      ---
      :rubygems_api_key: ${RUBYGEMS_API_KEY}
      EOF
    - chmod 0600 ~/.gem/credentials
    - cat ~/.gem/credentials
    - gem push ./$GEM_NAME-${CI_COMMIT_TAG}.gem
  only:
    - tags
